name: Multi OS Test # Multi OS Test Workflow

on: [push]

jobs: # Define jobs for different operating systems
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Details
        run: |
          echo "OS: Ubuntu"
          hostname
          whoami

      - name: Check Pre-installed Tools   # 👈 Task 2 added here
        run: |
          echo "Docker Version:"
          docker --version

          echo "Python Version:"
          python3 --version

          echo "Node Version:"
          node --version

          echo "Git Version:"
          git --version
          
  windows-job:
    runs-on: windows-latest
    steps:
      - name: Print Details
        run: |
          echo OS: Windows
          hostname
          whoami

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Print Details
        run: |
          echo "OS: macOS"
          hostname
          whoami